############
## Queue Group Configuration. The queue stats will be grouped by the 'groupName'
## if the 'queueNameRegex' matches the name of the Queue.

## groupName            The stats from Queues matched by the 'queueNameRegex' will be reported under this name
## queueNameRegex       A Regex to match the Queue Name
## showIndividualStats  If set to false then the Individual Queue stats will not be reported.
##                      This will help if there are several short lived queues and an explosion of metrics
##                      in the controller can be avoided
############

# Uncomment the following lines for configuration
queueGroups:
- groupName: group1
  queueNameRegex: queue.+
  showIndividualStats: true

# Queue Group Configuration
#- groupName: group2
#  queueNameRegex: temp.+
#  showIndividualStats: false

excludeQueueRegex: ^[0-9]*

encryptionKey: "myKey"

servers:

   - host: "localhost"
     port: 15672
     useSSL: false
     username: "guest"
     password: "guest"
     encryptedPassword: ""
     connectTimeout: 10000
     socketTimeout: 10000
     displayName : "Server2"

# number of concurrent tasks
numberOfThreads: 5

endpointFlags:
  federationPlugin: "false"
  overview: "true"

dictionary:
  #ack: "Acknowledged"
  #deliver: "Delivered"
  #deliver_get: "Delivered (Total)"
  #deliver_no_ack: "Delivered No-Ack"
  #get: "Got"
  #get_no_ack: "Got No-Ack"
  #publish: "Published"
  #redeliver: "Redelivered"
  #messages_ready: "Available"
  #messages_unacknowledged: "Pending Acknowledgements"
  #consumers: "Count"
  #active_consumers: "Active"
  #idle_consumers: "Idle"
  #slave_nodes: "Slaves Count"
  #synchronised_slave_nodes: "Synchronized Slaves Count"
  #down_slave_nodes: "Down Slaves Count"
  #messages: "Messages"

#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
#   multiplier -->not for derived metrics
#   convert --> not for derived metrics
#   delta --> not for derived metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

metrics:
     #Items in Nodes|<node>|Messages - data looked up from /api/channels
   - channelNodeMsgProps:
         - name: "ack"
           delta: "true"
           alias: "Acknowledged"
         - name: "deliver"
           alias: "Delivered"
         - name: "deliver_no_ack"
           alias: "Delivered No-Ack"
           delta: "true"
         - name: "get_no_ack"
           alias: "Got No-Ack"
         - name: "publish"
           alias: "Published"
           delta: "true"
         - name: "redeliver"
           alias: "Redelivered"
     #Queue Group data, stats combined by groupName defined in queueGroups above
   - queueGroupProps:
         - name: "consumers"
           alias: "Count"
     #Items in Nodes|<node>|Messages - data looked up from /api/queues
   - queueNodeMsgProps:
         - name: "messages_ready"
           alias: "Available"
         - name: "messages_unacknowledged"
           alias: "Pending Acknowledgements"
     #Items in Nodes|<node>|Consumers - data looked up from /api/queues
   - queueNodeProps:
         - name: "consumers"
           alias: "Count"
     #Items in Queues|<host>|<QName>|Messages - data looked up from /api/queues
   - queueMessageProps:
         - name: "messages_ready"
           alias: "Available"
         - name: "messages_unacknowledged"
           alias: "Pending Acknowledgements"
     #Items in Queues|<host>|<QName>|Replication - data looked up from /api/queues
   - queueReplicationCountsProps:
         - name: "slave_nodes"
           alias: "Slaves Count"
         - name: "synchronised_slave_nodes"
           alias: "Synchronized Slaves Count"
         - name: "down_slave_nodes"
           alias: "Down Slaves Count"
     #Items in Queues|<host>|<QName>|Messages - data looked up from /api/queues/message_stats
   - queueMessageStatsProps:
         - name: "ack"
           alias: "Acknowledged"
         - name: "deliver_get"
           alias: "Delivered (Total)"
           delta: "true"
         - name: "deliver"
           alias: "Delivered"
           delta: "true"
         - name: "deliver_no_ack"
           alias: "Delivered No-Ack"
         - name: "get"
           alias: "Got"
         - name: "get_no_ack"
           alias: "Got No-Ack"
         - name: "publish"
           alias: "Published"
         - name: "redeliver"
           alias: "Redelivered"
     #Items in Summary|Messages - data looked up from /api/queues
   - queueSummaryProps:
         - name: "messages_ready"
           delta: "true"
           alias: "Available"
         - name: "deliver_get"
           alias: "Delivered (Total)"
           delta: "true"
         - name: "publish"
           alias: "Published"
           delta: "true"
         - name: "redeliver"
           delta: "true"
           alias: "Redelivered"
         - name: "messages_unacknowledged"
           alias: "Pending Acknowledgements"
           delta: "true"
     #Items in Clusters|<Cluster>|Queues - data looked up from /api/overview
   - queueTotalsProps:
         - name: "messages"
           alias: "Messages"
         - name: "messages_ready"
           alias: "Available"
         - name: "messages_unacknowledged"
           alias: "Pending Acknowledgements"
     #Items in Clusters|<Cluster>|Messages - data looked up from /api/overview
   - messageTotalsProps:
         - name: "publish"
           alias: "Published"
         - name: "deliver_get"
           alias: "Delivered (Total)"
         - name: "ack"
           alias: "Acknowledged"
         - name: "get"
           alias: "Got"
     #Items in Clusters|<Cluster>|Objects - data looked up from /api/overview
   - objectTotalsProps:
         - name: "consumers"
           alias: "Count"
         - name: "queues"
         - name: "exchanges"
         - name: "connections"
         - name: "channels"
    #Items in Nodes|<node> - data looked up from /api/nodes
   - nodeDataMetrics:
         - name: "proc_used"
           prefix: "Erlang Processes"
         - name: "disk_free_alarm"
           prefix: "Disk Free Alarm Activated"
         - name: "mem_alarm"
           prefix: "Memory Free Alarm Activated"
         - name: "fd_used"
           prefix: "File Descriptors"
         - name: "mem_used"
           divisor: "1048576"
           prefix: "Memory(MB)"
         - name: "sockets_used"
           prefix: "Sockets"
         - name: "channels_count"
           prefix: "Channels|Count"
         - name: "channels_blocked"
           prefix: "Channels|Blocked"
         - name: "summary_channels"
           prefix: "Summary|Channels"
         - name: "consumers"
           prefix: "Summary|Consumers"

#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics | RabbitMQ |

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|RabbitMQ|